# Generated by Django 6.0.2 on 2026-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('Image', models.ImageField(upload_to='employee')),
            ],
        ),
    ]
